version: "3.3"

services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - variables.env
    volumes:
      - ./postgres-storage/data:/var/lib/postgresql/data

  rosseti-back:
    depends_on:
      - postgres
    build: ./
    image: sqsinformatique/rosseti-back
    env_file:
      - variables.env
    command: serve
    ports:
      - "9000:9000"
      - "9100:9100"
    restart: on-failure
