version: "3.3"

services:
  modgodb:
    image: mongo:3.6.20-xenial
    ports:
      - "27017:27017"
    env_file:
      - variables.env

  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - variables.env

  rosseti-back:
    depends_on:
      - modgodb
      - postgres
    build: ./
    image: sqsinformatique/rosseti-back
    env_file:
      - variables.env
    command: serve
    ports:
      - "9000:9000"
      - "9100:9100"
    restart: on-failure
